package notifier.senders;

import no.vianett.sms.SmsEventListener;

import java.io.IOException;

import org.json.simple.parser.ParseException;

import exceptions.BadLengthTelephoneNumberException;
import exceptions.SenderException;
import no.vianett.sms.Sms;
import no.vianett.sms.SmsEvent;
import no.vianett.sms.component.SmsTransceiver;
import no.vianett.sms.log.SmsScreenLogger;
import no.vianett.sms.event.SmsDeliveredEvent;
import no.vianett.sms.event.SmsSendingFailedEvent;
import no.vianett.sms.event.SmsDeliveryFailedEvent;
 
public class SmsSender extends Sender implements SmsEventListener
{
    private SmsTransceiver transceiver = null;
    private int counter = 0;
    
 
    public SmsSender(String configFilePath) throws IOException, ParseException
    {
    	super(configFilePath);   
    }
    
    
    public synchronized void configure() {
    	if(!this.configured) {
    		this.transceiver = SmsTransceiver.getInstance(); // Get the transceiver object.
            this.transceiver.initialize( this.host, Integer.parseInt( this.port ), this.nick, this.password, new SmsScreenLogger() );
            this.transceiver.addSmsEventListener( this ); // Registrer this class as listener for SMS events.
            this.configured = true;
    	}
    }
    /**
    * Listener.
    *
    * @param event a <code>no.vianett.sms.SmsEvent</code>
    */
    public void eventHappened( SmsEvent event )
    {
        if( event instanceof SmsDeliveredEvent )
        {
            System.out.println( "Sms delivered." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsSendingFailedEvent )
        {
            System.out.println( "Sms sending failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Return code : " + ( ( SmsSendingFailedEvent ) event ).getReturnCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsDeliveryFailedEvent )
        {
            System.out.println( "Sms delivery failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Error code : " + ( ( SmsDeliveryFailedEvent ) event ).getErrorCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
    }

	@Override
	public void send(String contact, String title, String message) throws SenderException {
		
		
		if(contact.length()<=8 || contact.length()>=11) {
			throw new SenderException(new BadLengthTelephoneNumberException());
		}
		
		
		if(!this.configured) {
			this.configure();
		}
		
		
		 // Send message
        Sms sms = new Sms();
        sms.setId( ++this.counter );
        sms.setReplyPath( 100 );
        sms.setSender( "1963" ); // Set the sender number.
        sms.setHeader(title);
        sms.setMessage( message );
        sms.setRecipient( contact ); // The recipients phone number.
 
       this.transceiver.send( sms );

		
	}
	
	
 
}