package notifier.senders;

import no.vianett.sms.SmsEventListener;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import no.vianett.sms.Sms;
import no.vianett.sms.SmsEvent;
import no.vianett.sms.component.SmsTransceiver;
import no.vianett.sms.log.SmsScreenLogger;
import no.vianett.sms.event.SmsDeliveredEvent;
import no.vianett.sms.event.SmsSendingFailedEvent;
import no.vianett.sms.event.SmsDeliveryFailedEvent;
 
public class SmsSender implements SmsEventListener,Sendable
{
    private SmsTransceiver transceiver = null;
    private int counter = 0;
    private String nick;
	private String password;
	private String host;
	private String port;
 
    public SmsSender(String configFilePath)
    {
    	
    	InputStream inputStream = MailSender.class.getResourceAsStream(configFilePath);
	 	BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
		JSONParser parser = new JSONParser();
		
		try {
			
			Object obj = parser.parse(reader);
			JSONObject jsonObject = (JSONObject) obj;
			
			this.nick = (String) jsonObject.get("nick");
			this.password = (String) jsonObject.get("password");
			this.host = (String) jsonObject.get("host");
			this.port = (String) jsonObject.get("port");
			
			System.out.println(nick);
			System.out.println(password);
			System.out.println(host);
			System.out.println(port);
			
			this.transceiver = SmsTransceiver.getInstance(); // Get the transceiver object.
	        this.transceiver.initialize( this.host, Integer.parseInt( this.port ), this.nick, this.password, new SmsScreenLogger() );
	        this.transceiver.addSmsEventListener( this ); // Registrer this class as listener for SMS events.
	        
			reader.close();
			
			
		} catch (IOException | ParseException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        
    }
 
    /**
    * Listener.
    *
    * @param event a <code>no.vianett.sms.SmsEvent</code>
    */
    public void eventHappened( SmsEvent event )
    {
        if( event instanceof SmsDeliveredEvent )
        {
            System.out.println( "Sms delivered." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsSendingFailedEvent )
        {
            System.out.println( "Sms sending failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Return code : " + ( ( SmsSendingFailedEvent ) event ).getReturnCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsDeliveryFailedEvent )
        {
            System.out.println( "Sms delivery failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Error code : " + ( ( SmsDeliveryFailedEvent ) event ).getErrorCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
    }

	@Override
	public void send(String contact, String title, String message) {
		 // Send message
        Sms sms = new Sms();
        sms.setId( ++this.counter );
        sms.setReplyPath( 100 );
        sms.setSender( "1963" ); // Set the sender number.
        sms.setHeader(title);
        sms.setMessage( message );
        sms.setRecipient( contact ); // The recipients phone number.
 
       this.transceiver.send( sms );

		
	}
 
}